app/core/urls.py
from django.conf.urls import patterns, url
from core.views import *

urlpatterns = patterns('',
    url(r'^$', HomePageView.as_view(), name='test'),

    url(r'^test/$', test, name='test'),

    url(r'^leads/$', UserBidsListView.as_view(), name='user_leads'),
    url(r'^stats/$', UserStatisticsView.as_view(), name='user_stats'),
    url(r'^settings/$', UserSettingsView.as_view(), name='user_settings'),

    url(r'^company/$', UserProfileView.as_view(), name='user_company'),
    url(r'^company/form/sidebar/$', company_form_sidebar, name='user_company_form_sidebar'),
    url(r'^company/form/popup/add/$', company_form_popup_add, name='user_company_form_popup_add'),

    url(r'^billing/payment-form/$', order_page, name='user_billing_order'),
    url(r'^billing/$', UserBalanceView.as_view(), name='user_billing'),


    #url(r'^bids/commentary/(?P<id>.*)/save/$', user_bid_commentary_save(), name='user_commentary_bid_save'),


)

oxiv/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from rest_framework import routers
from yandex_money.views import CheckOrderFormView
from yandex_money.views import NoticeFormView
from accounts.views import new_registration_user
from core.views import UserBalanceView, test_aviso, test_check_order

admin.autodiscover()



urlpatterns = [
    #url("", include("django_socketio.urls")),
    #url('^chat/', include("chat.urls")),

    url('', include('core.urls', namespace="core")),
    url('^adm/', include('padmin.urls', namespace="padmin")),
    url('^api/', include('api.urls', namespace="api_websocket")),
    url('^manager/', include('core.urls', namespace="manager")),

    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),

    url(r'^registration/', new_registration_user, name='new_registration_user'),

    url(r'^accounts/', include('registration.backends.default.urls')),

    url(r'^fail-payment/$', UserBalanceView.as_view(), name='payment_fail'),
    url(r'^success-payment/$', UserBalanceView.as_view(), name='payment_success'),

    #url(r'^yandex-money/aviso/$', test_aviso, name='test_aviso'),
    #url(r'^yandex-money/check/$', test_check_order, name='test_check_order'),
    url(r'^yandex-money/check/$', CheckOrderFormView.as_view(), name='yandex_money_check'),
    url(r'^yandex-money/aviso/$', NoticeFormView.as_view(), name='yandex_money_notice'),

    #url(r'^yandex-money/', include('yandex_money.urls')),


    url(r'^admin/', include(admin.site.urls)),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from core.models import UserSettings, ProductsAndService

"""
#
# FORM SIDEBAR COMPANY
#
"""
class FormSidebarCompany(forms.ModelForm):
    company_name = forms.CharField(required=True)
    phone = forms.CharField(required=True)


    class Meta:
        model = UserSettings
        fields = ('city', 'address', 'mode_job', 'site_url')
        exclude = ('user', 'topics', 'status')

"""
#
# FORM POPUP ADD COMPANY
#
"""
class FormPopupAddCompany(forms.ModelForm):

    class Meta:
        model = ProductsAndService
        exclude = ('user',)

app/core/views.py
# -*- coding: utf-8 -*-
import hashlib
import httplib
import json
import urllib
from django.conf import settings
from django.core import serializers
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.views.generic import TemplateView
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from yandex_money.forms import PaymentForm
from yandex_money.models import Payment
from accounts.models import UserProfile, UserNotification
from core.api import YandexApi
from core.forms import FormSidebarCompany, FormPopupAddCompany
from core.http import JSONResponseMixin
from core.models import UserBids, Topics, UserSettings, StatusBids, ProductsAndService
from core.serializers import ProductsAndServiceSerializer, UserBidsSerializer
from payment.models import Order, HistoryDebit
from payment.serializers import OrderSerializer, HistoryDebitSerializer


def test(request):
    if request.GET['code']:
        #Формирование параметров (тела) POST-запроса с указанием кода подтверждения
        query = {
            'grant_type': 'authorization_code',
            'code': request.GET['code'],
            'client_id': '0cd94059e3ea4276b204fd744bea18ac',
            'client_secret': '1dd4715ab28d40cc9c08d8a09d7f2e5e',
        }
        query = urllib.urlencode(query)

        #Формирование заголовков POST-запроса
        header = {
            'Content-Type': 'application/x-www-form-urlencoded'
        }

        #Выполнение POST-запроса и вывод результата
        connection = httplib.HTTPSConnection('oauth.yandex.ru')
        connection.request('POST', '/token', query, header)
        response = connection.getresponse()
        result = response.read()
        connection.close()
        tmp_filename = settings.TMP_PATH + '/messages.txt'
        with open(tmp_filename, "wb") as f:
           f.write(json.loads(result)['access_token'])
        f.close()

        #Токен необходимо сохранить для использования в запросах к API Директа
        return json.loads(result)['access_token']



class HomePageView(TemplateView):
    template_name = 'registration/registration_form.html'

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated():
                return redirect('http://i.oxiv.ru/')
        else:
            return redirect('core:user_leads')
        return super(HomePageView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        #res = YandexApi(method='GetSummaryStat')
        #print(res.result())
        return context

"""
#
# A list of bids the user (Список заявок пользователя)
#
"""
class UserBidsListView(TemplateView):
    template_name = 'core/bids.html'

    def dispatch(self, *args, **kwargs):
        #if not self.request.user.is_authenticated():
                #return redirect('auth_login')
        return super(UserBidsListView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        GET = self.request.GET

        if 'type' in GET:
            if GET['value'] == 'lead':
                lead_id = GET.get('lead', None)

                item = UserBids.objects.get(id=lead_id, user=self.request.user)
                content = JSONResponseMixin(UserBidsSerializer(item).data)

                return content
        else:
            return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(UserBidsListView, self).get_context_data(**kwargs)
        context['user_bids'] = UserBids.objects.filter(user=self.request.user)
        context['settings'] = UserSettings.objects.get(user=self.request.user)
        return context

"""
#
# A statistics' the user (Статистика пользователя)
#
"""
class UserStatisticsView(TemplateView):
    template_name = 'core/statistics.html'

    def dispatch(self, *args, **kwargs):
        #if not self.request.user.is_authenticated():
                #return redirect('auth_login')
        return super(UserStatisticsView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserStatisticsView, self).get_context_data(**kwargs)
        return context


"""
#
# The profile user (Профиль пользователя)
#
"""
class UserProfileView(TemplateView):
    template_name = 'core/profile.html'

    def dispatch(self, *args, **kwargs):
        #if not self.request.user.is_authenticated():
                #return redirect('auth_login')
        return super(UserProfileView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        GET = self.request.GET

        if 'type' in GET:
            if GET['value'] == 'product':
                product_id = GET.get('product', None)

                item = ProductsAndService.objects.get(id=product_id, user=self.request.user)
                content = JSONResponseMixin(ProductsAndServiceSerializer(item).data)

                return content
        else:
            return self.render_to_response(context)



    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        obj = UserSettings.objects.get(user=self.request.user)

        initial_frmsc = {
            'company_name': self.request.user.first_name,
            'phone': self.request.user.phone,
        }
        context['frmsc'] = FormSidebarCompany(instance=obj, initial=initial_frmsc)
        context['frmpac'] = FormPopupAddCompany()
        context['products_items'] = ProductsAndService.objects.filter(user=self.request.user).order_by('-created')
        return context

"""
#
# VIEWS FORM SIDEBAR COMPANY
#
"""
def company_form_sidebar(request):
    context = {}
    obj = UserSettings.objects.get(user=request.user)

    if request.POST:
        form = FormSidebarCompany(request.POST, instance=obj)
        if form.is_valid():
            frm = form.save(commit=False)
            frm.user = request.user
            frm.save()

            user = UserProfile.objects.get(id=request.user.id)
            user.first_name = form.cleaned_data.get('company_name', None)
            user.phone = form.cleaned_data.get('phone', None)
            user.save()

            context['result'] = 'success'
        else:
            context = dict(form.errors.items())

    return JsonResponse(context)

"""
#
# VIEWS FORM POPUP aDD COMPANY
#
"""
def company_form_popup_add(request):
    context = {}
    data = {}

    if request.user.is_anonymous():
        return False

    if request.POST:
        if 'id' in request.POST and 'change' in request.POST:
            item = ProductsAndService.objects.get(id=request.POST['id'], user=request.user)
            form = FormPopupAddCompany(request.POST, instance=item)
            if form.is_valid():
                frm = form.save(commit=False)
                frm.user = request.user
                frm.save()

                if 'image' in request.FILES:
                    frm.image = request.FILES['image']
                    frm.save()

                context['result'] = 'success'
                data['item'] = frm
                context['id'] = frm.id
                context['html'] = render_to_string("core/profile-product-only.html", data)
            else:
                context = dict(form.errors.items())
        if 'id' not in request.POST:
            form = FormPopupAddCompany(request.POST)
            if form.is_valid():
                frm = form.save(commit=False)
                frm.user = request.user
                frm.is_active = False
                frm.save()

                if 'image' in request.FILES:
                    frm.image = request.FILES['image']
                    frm.save()

                context['result'] = 'success'
                data['item'] = frm
                context['id'] = frm.id
                context['html'] = render_to_string("core/profile-product-only.html", data)
            else:
                context = dict(form.errors.items())
    elif request.GET:
        type = request.GET.get('type', None)
        id = request.GET.get('id', None)

        if type == 'confirm':
            item = ProductsAndService.objects.get(id=id, user=request.user)
            item.is_active = True
            item.save()
        elif type == 'delete':
            ProductsAndService.objects.get(id=id, user=request.user).delete()

        elif type == 'confrim_edit':
            pass

    return JsonResponse(context)
"""
#
# Save commentary bid list user
#
"""
def user_bid_commentary_save(request, id):
    print(id)
    return  json.dumps({'success:true'})



"""
#
# PAGE BALANCE СТРАНИЦА БАЛАНСА
#
"""

"""
#
# PAGE BALANCE (Страница баланса)
#
"""
class UserBalanceView(TemplateView):
    template_name = 'core/balance.html'

    def dispatch(self, *args, **kwargs):
        #if not self.request.user.is_authenticated():
                #return redirect('auth_login')
        return super(UserBalanceView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        GET = self.request.GET
        print(GET.items())

        if 'type' in GET:
            if GET['type'] == 'order':
                count = int(GET.get('count', None)) - 1
                count_end = count + 6
                last = False

                if Order.objects.filter(user=self.request.user)[count_end:count_end+1]:
                    last = True

                items = Order.objects.filter(user=self.request.user)[count:count_end]
                result = [OrderSerializer(item).data for item in items]
                result.append({'last': last})

            elif GET['type'] == 'debit':
                count = int(GET.get('count', None)) - 1

templates/core/balance.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Баланс | Oxiv.ru{% endblock %}
{% block description %}Какое та описание{% endblock %}
{% block canonical %}{% endblock %}

{% block style %}

{% endblock %}

{% block style_page %}page-content container-fluid{% endblock %}

{% block page_title %}Баланс{% endblock %}
{% block content %}

<div class="col-lg-12 col-md-18">
          <div class="row">
            <div class="col-md-4">
              <div class="widget">
                <div  class="widget-content padding-25  height220 bg-white">
                  <div style="padding-top: 45.3px;" class="counter counter-lg">
                    <span class="counter-number">{{ request.user.get_balance }} руб.</span>
                    <div class="counter-label">Остаток</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="widget">
                <div class="widget-content padding-25 height220 bg-white">
                  <form method="POST" action="{% url 'core:user_billing_order' %}" class="form-horizontal fv-form fv-form-bootstrap ajaxify-form" id="FormBillingUser" data-submit="FormBillingUser" >
                  <div class="counter counter-lg counter-inverse">{% csrf_token %}
                    <div style="margin-bottom: 39px;" class="counter-label ">


                <div class="form-group form-material floating">
                  <div class="input-group">

                    <div class="form-control-wrap">
                      <input name="vMin" data-fv-greaterthan="true" data-fv-greaterthan-value="1" data-fv-greaterthan-message="Минимальная сумма: 1 руб."  data-fv-field="vMin" type="text" class="form-control empty" required>
                      <label class="floating-label">Введите сумму</label>
                    </div>
                    <span class="input-group-addon">руб.</span>
                  </div>
                </div>

                    </div>
                    <span class="counter-number"><button type="submit"  class="btn btn-primary btn-default padding70">Внести платеж</button></span>
                  </div>
                    </form>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="widget">
                <div class="widget-content padding-25 height220 bg-white">
                    <form>
                  <div class="counter counter-lg counter-inverse">
                    <div style="margin-bottom: 39px;" class="counter-label ">

                <div class="form-group form-material floating">
                  <input type="text" class="form-control empty" name="inputFloatingText">
                  <label class="floating-label">Промокод</label>
                </div>

                    </div>
                    <span class="counter-number"><button type="button" class="btn btn-outline btn-default padding70">Активировать</button></span>
                  </div>
                    </form>
                </div>
              </div>
            </div>
          </div>
</div>

{% include 'core/billing-form-payment.html' %}

<div class="col-md-6 col-xs-12 masonry-item" >
          <!-- Panel Sales -->
          <div class="panel">
            <div class="panel-heading">
              <h3 class="panel-title">История платежей</h3>
            </div>
            <div class="table-responsive">
              <table class="table table-hover table-striped table-orders">
                <thead>
                  <tr>
                    <th>ID #</th>
                    <th>Дата</th>
                    <th>Время</th>
                    <th>Сумма</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                {% for order in orders %}
                  <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.created|date:"j.n.Y" }}</td>
                    <td>{{ order.created|date:"H:i" }}</td>
                    <td>+ {{ order.amount }} руб.</td>
                    <td>
                      <span data-plugin="peityBar" style="display: none;">2,3,2,-1,-3,-2,2,3,5,4</span><svg class="peity" height="22" width="44"><rect fill="#a2caee" x="0.44000000000000006" y="8.25" width="3.52" height="5.5"></rect><rect fill="#a2caee" x="4.840000000000001" y="5.5" width="3.5199999999999987" height="8.25"></rect><rect fill="#a2caee" x="9.24" y="8.25" width="3.5199999999999996" height="5.5"></rect><rect fill="#a2caee" x="13.64" y="13.75" width="3.5199999999999996" height="2.75"></rect><rect fill="#a2caee" x="18.04" y="13.75" width="3.520000000000003" height="8.25"></rect><rect fill="#a2caee" x="22.439999999999998" y="13.75" width="3.520000000000003" height="5.5"></rect><rect fill="#a2caee" x="26.839999999999996" y="8.25" width="3.5200000000000067" height="5.5"></rect><rect fill="#a2caee" x="31.24" y="5.5" width="3.5200000000000067" height="8.25"></rect><rect fill="#a2caee" x="35.64" y="0" width="3.520000000000003" height="13.75"></rect><rect fill="#a2caee" x="40.04" y="2.75" width="3.520000000000003" height="11"></rect></svg>
                    </td>
                  </tr>
                {% endfor %}

                </tbody>
              </table>
            </div>
            <div class="panel-footer">
              <a class="blue-grey-500 action-button " data-callback="BillingOrdersPageShowMore"><i class="icon wb-info-circle blue-600 margin-right-10" aria-hidden="true"></i>Показать еще</a>
            </div>
          </div>
          <!-- End Panel Sales -->
        </div>



<div class="col-md-6 col-xs-12 masonry-item" >
          <!-- Panel Sales -->
          <div class="panel">
            <div class="panel-heading">
              <h3 class="panel-title">История списаний</h3>
            </div>
            <div class="table-responsive">
              <table class="table table-hover table-striped table-debits">
                <thead>
                  <tr>
                    <th>ID #</th>
                    <th>Дата</th>
                    <th>Время</th>
                    <th>Назначение</th>
                    <th>Сумма</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                {% for debit in debits %}
                  <tr>
                    <td>{{ debit.id }}</td>
                    <td>{{ debit.created|date:"j.n.Y" }}</td>
                    <td>{{ debit.created|date:"H:i" }}</td>
                    <td><a href="#">Заявка №{{ debit.leads.id }}</a></td>
                    <td>- {{ debit.amount }} руб.</td>
                    <td>
                      <span data-plugin="peityBar" style="display: none;">2,3,2,-1,-3,-2,2,3,5,4</span><svg class="peity" height="22" width="44"><rect fill="#a2caee" x="0.44000000000000006" y="8.25" width="3.52" height="5.5"></rect><rect fill="#a2caee" x="4.840000000000001" y="5.5" width="3.5199999999999987" height="8.25"></rect><rect fill="#a2caee" x="9.24" y="8.25" width="3.5199999999999996" height="5.5"></rect><rect fill="#a2caee" x="13.64" y="13.75" width="3.5199999999999996" height="2.75"></rect><rect fill="#a2caee" x="18.04" y="13.75" width="3.520000000000003" height="8.25"></rect><rect fill="#a2caee" x="22.439999999999998" y="13.75" width="3.520000000000003" height="5.5"></rect><rect fill="#a2caee" x="26.839999999999996" y="8.25" width="3.5200000000000067" height="5.5"></rect><rect fill="#a2caee" x="31.24" y="5.5" width="3.5200000000000067" height="8.25"></rect><rect fill="#a2caee" x="35.64" y="0" width="3.520000000000003" height="13.75"></rect><rect fill="#a2caee" x="40.04" y="2.75" width="3.520000000000003" height="11"></rect></svg>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
            <div class="panel-footer">
              <a class="blue-grey-500 action-button " data-callback="BillingDebitsPageShowMore"><i class="icon wb-info-circle blue-600 margin-right-10" aria-hidden="true"></i>Показать еще</a>
            </div>
          </div>
          <!-- End Panel Sales -->
        </div>

{% endblock %}

{% block script_bottom %}
<script type="text/javascript">
  function paymentChoice(val, el){
      $('.field-payment').not($(el)).removeClass('active');
      console.log($(el).toggleClass('active'));

      $('#id_paymentType option')
     .removeAttr('selected')
     .filter('[value='+val+']')
         .attr('selected', true)
  }
 function ClosePaymentFinal(el){
      $('#UserPaymentFillIn').modal('hide');
     return true
  }
</script>
{% endblock %}

templates/core/order-page.html
{% load staticfiles %}
{% load thumbnail %}
<form name="ShopForm" method="POST" action="https://money.yandex.ru/eshop.xml" target="_blank">
      <div id="FormBillingFinal">
          <div style="display:none">
              {{ form.shopId }}
          {{ form.scid }}
          {{ form.orderNumber }}
          {{ form.customerNumber }}
          {{ form.sum }}
          {{ form.cps_email }}
          {{ form.cps_phone }}
          {{ form.shopFailURL }}
          {{ form.shopSuccessURL }}
          {{ form.paymentType }}
          </div>
          <div class="content-form">

              <div class="row">
            <div class="col-md-3">
              <div style="border: 1px solid #ededed;" class="widget">
                <div onClick="paymentChoice('AC', this);" class="widget-content padding-25 field-payment bg-white">
                  <div class="counter counter-lg">
                    <div class="counter-number payment-big-icons-bankcards"></div>
                    <div class="counter-label">Банковские карты</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div style="border: 1px solid #ededed;" class="widget">
                <div onClick="paymentChoice('PC', this);" class="widget-content padding-25 active field-payment bg-white">
                  <div class="counter counter-lg">
                    <div class="counter-number payment-big-icons-yandex-dengi"></div>
                    <div class="counter-label">Яндекс деньги</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div style="border: 1px solid #ededed;" class="widget">
                <div onClick="paymentChoice('WM', this);" class="widget-content padding-25 field-payment  bg-white">
                  <div class="counter counter-lg">
                    <div class="counter-number payment-big-icons-webmoney-rub"></div>
                    <div class="counter-label">Webmoney</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div style="border: 1px solid #ededed;" class="widget">
                <div onClick="paymentChoice('GP', this);" class="widget-content padding-25 field-payment bg-white">
                  <div class="counter counter-lg">
                    <div class="counter-number payment-big-icons-terminals"></div>
                    <div class="counter-label">Наличными в терминале</div>
                  </div>
                </div>
              </div>
            </div>
          </div>

               <div class="row">
            <div class="col-md-3">
              <div style="border: 1px solid #ededed;" class="widget">
                <div onClick="paymentChoice('SB', this);" class="widget-content padding-25 field-payment bg-white">
                  <div class="counter counter-lg">
                    <div class="counter-number payment-big-icons-sb-online"></div>
                    <div class="counter-label">Сбербанк онлайн</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div style="border: 1px solid #ededed;" class="widget">
                <div onClick="paymentChoice('AB', this);" class="widget-content padding-25 field-payment bg-white">
                  <div class="counter counter-lg">
                    <div class="counter-number payment-big-icons-alfa-click"></div>
                    <div class="counter-label">Альфа-клик</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div style="border: 1px solid #ededed;" class="widget">
                <div onClick="paymentChoice('PB', this);" class="widget-content padding-25 field-payment  bg-white">
                  <div class="counter counter-lg">
                    <div class="counter-number payment-big-icons-promsvyaz"></div>
                    <div class="counter-label">Промсвязьбанк</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div style="border: 1px solid #ededed;" class="widget">
                <div onClick="paymentChoice('MA', this);" class="widget-content padding-25 field-payment bg-white">
                  <div class="counter counter-lg">
                    <div class="counter-number payment-big-icons-masterpass"></div>
                    <div class="counter-label">Masterpass</div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          </div>







          <div class="bottom_form">
              <button type="submit" onClick="ClosePaymentFinal(this);" class="btn btn-block btn-primary padding60">Оплатить 200 руб.</button>
          </div>

      </div>

</form>

templates/core/profile-adv-edit-from.html
{% load staticfiles %}
<!-- Modal -->
                        <div class="modal fade serv-edit-sidebar sidebar-right-form" id="ServEditPositionSidebar" aria-hidden="true" aria-labelledby="examplePositionSidebar" role="dialog" tabindex="-1" >
                          <div class="modal-dialog profile-adv modal-sidebar modal-sm" >
                                  <div class="widget-header height-auto bg-blue-600 vertical-align padding-vertical-20 padding-horizontal-25">
              <blockquote style="border-left:none;    padding: initial;" class=" vertical-align-middle white font-size-20"><span class="inputTextTitle">Ремонт компьютеров</span> - <span class="inputTextCost">2000 руб.</span> </blockquote>
            </div>
       <form data-submit="FormPopupEditCompany"  enctype="multipart/form-data" id="FormPopupEditCompany" class="ajaxify-form form_popup_add_company" method="POST" action="{% url 'core:user_company_form_popup_add' %}">
<input name="id" style="display: none;">{% csrf_token %}
                   <div class="widget-body padding-top-0" style="margin-top: -64px">
              <div style="    width: 120px;height: 120px" class="avatar avatar-lg img-bordered bg-white margin-bottom-10">
                <img title="Загрузить фото..." id="output" width="120px" height="120px" src="{% static 'images/none_img.png' %}" alt="">
                  <label class="upload_field">
          <input style="display: none" name="image" type="file" id="screenshot" accept="image/png" onchange="loadFile(event)"/>

                      </label>
              </div>
            </div>


                            <div class="modal-content">
                                <a style="display: block" title="Удалить" type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <i class="icon ion-ios-close-outline" aria-hidden="true"></i>
                                </a>
<div class="modal-body">

                <div class="form-group form-material floating">
                  <input type="text" class="form-control" id="inputTextTitle"  name="name">
                  <label class="floating-label">Название</label>
                </div>

                <div style="width: 50%;float: left;" class="form-group  form-material floating">
                    <div  class="input-group">
                        <div class="form-control-wrap">
                  <input type="text" class="form-control" id="inputTextCost" name="price_from">
                  <label class="floating-label">Цена (от)</label>
                            </div>
                        <span class="input-group-addon">руб.</span>
                   </div>
                </div>
                 <div style="width: 50%;float: left;" class="form-group  form-material floating">
                    <div  class="input-group">
                        <div class="form-control-wrap">
                  <input type="text" class="form-control" id="inputTextCost" name="price_to">
                  <label class="floating-label">Цена (до)</label>
                            </div>
                        <span class="input-group-addon">руб.</span>
                   </div>

                </div>
                <div style="clear:both"></div>


               <div class="form-group form-material floating">
                  <input type="url" class="form-control" name="url">
                  <label class="floating-label">Ссылка</label>
                </div>


                <div class="form-group form-material floating">
                  <textarea class="form-control" id="textarea" name="description" rows="5"></textarea>
                  <label class="floating-label">Описание</label>
                </div>



</div>
                              <div class="modal-footer profile-add-adv">
                                <button type="submit" class="btn btn-block btn-primary">Сохранить</button>
                                <button type="button" class="btn btn-outline btn-default" data-dismiss="modal">Отменить</button>
                                <button data-callback="ServEditServiceDelete" type="button" class="btn action-button btn-outline btn-danger" data-dismiss="modal">Удалить</button>
                              </div>
</form>
</div>
                          </div>
                        </div>
                        <!-- End Modal -->
<script>
    /* Input image preview */
var loadFile = function(event) {
	var output = document.getElementById('output');
	output.src = URL.createObjectURL(event.target.files[0]);
    console.log(output.src);
};
</script>