app/core/urls.py
from django.conf.urls import patterns, url
from core.views import *

urlpatterns = patterns('',
    url(r'^$', HomePageView.as_view(), name='test'),

    url(r'^test/$', test, name='test'),

    url(r'^leads/$', UserBidsListView.as_view(), name='user_leads'),
    url(r'^stats/$', UserStatisticsView.as_view(), name='user_stats'),
    url(r'^settings/$', UserSettingsView.as_view(), name='user_settings'),

    url(r'^company/$', UserProfileView.as_view(), name='user_company'),
    url(r'^company/form/sidebar/$', company_form_sidebar, name='user_company_form_sidebar'),
    url(r'^company/form/popup/add/$', company_form_popup_add, name='user_company_form_popup_add'),

    url(r'^billing/payment-form/$', order_page, name='user_billing_order'),
    url(r'^billing/$', UserBalanceView.as_view(), name='user_billing'),


    #url(r'^bids/commentary/(?P<id>.*)/save/$', user_bid_commentary_save(), name='user_commentary_bid_save'),


)

oxiv/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from rest_framework import routers
from yandex_money.views import CheckOrderFormView
from yandex_money.views import NoticeFormView
from accounts.views import new_registration_user
from core.views import UserBalanceView, test_aviso, test_check_order

admin.autodiscover()



urlpatterns = [
    #url("", include("django_socketio.urls")),
    #url('^chat/', include("chat.urls")),

    url('', include('core.urls', namespace="core")),
    url('^adm/', include('padmin.urls', namespace="padmin")),
    url('^api/', include('api.urls', namespace="api_websocket")),
    url('^manager/', include('core.urls', namespace="manager")),

    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),

    url(r'^registration/', new_registration_user, name='new_registration_user'),

    url(r'^accounts/', include('registration.backends.default.urls')),

    url(r'^fail-payment/$', UserBalanceView.as_view(), name='payment_fail'),
    url(r'^success-payment/$', UserBalanceView.as_view(), name='payment_success'),

    #url(r'^yandex-money/aviso/$', test_aviso, name='test_aviso'),
    #url(r'^yandex-money/check/$', test_check_order, name='test_check_order'),
    url(r'^yandex-money/check/$', CheckOrderFormView.as_view(), name='yandex_money_check'),
    url(r'^yandex-money/aviso/$', NoticeFormView.as_view(), name='yandex_money_notice'),

    #url(r'^yandex-money/', include('yandex_money.urls')),


    url(r'^admin/', include(admin.site.urls)),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/bids.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Список заявок | Сайт oxiv{% endblock %}
{% block description %}Какое та описание{% endblock %}
{% block canonical %}{% endblock %}

{% block style_page %}page-content page-content-table{% endblock %}

{% block style %}
<!-- Page -->
  <link rel="stylesheet" href="{% static 'css/apps/contacts.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/bootstrap-select.min.css' %}">
{% endblock %}

{% block content %}
<!-- Actions -->
        <div style="display: none;" class="page-content-actions">
          <div class="pull-right">
            <div class="dropdown">
              <button type="button" class="btn btn-pure dropdown-toggle" data-toggle="dropdown"
              aria-expanded="false">
                More
                <span class="icon wb-chevron-down-mini" aria-hidden="true"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><a href="javascript:void(0)">More</a></li>
                <li><a href="javascript:void(0)">More</a></li>
              </ul>
            </div>
            <button type="button" class="btn btn-outline btn-default btn-md empty-btn">Empty All</button>
          </div>
          <div class="btn-group">
            <div class="dropdown">
              <button class="btn btn-icon btn-pure btn-default dropdown-toggle" data-toggle="dropdown"
              aria-expanded="false" type="button"><i class="icon wb-folder" aria-hidden="true"></i></button>
              <ul class="dropdown-menu" role="menu">
                <li><a href="javascript:void(0)">work</a></li>
                <li><a href="javascript:void(0)">Family</a></li>
                <li><a href="javascript:void(0)">Private</a></li>
                <li><a href="javascript:void(0)">Friends</a></li>
                <li class="divider"></li>
                <li><a href="javascript:void(0)">Trash</a></li>
                <li><a href="javascript:void(0)">Spam</a></li>
              </ul>
            </div>
            <div class="dropdown">
              <button class="btn btn-icon btn-pure btn-default dropdown-toggle" data-toggle="dropdown"
              aria-expanded="false" type="button"><i class="icon wb-tag" aria-hidden="true"></i></button>
              <ul class="dropdown-menu" role="menu">
                <li><a href="javascript:void(0)">work</a></li>
                <li><a href="javascript:void(0)">Family</a></li>
                <li><a href="javascript:void(0)">Private</a></li>
                <li><a href="javascript:void(0)">Friends</a></li>
              </ul>
            </div>
          </div>
        </div>

        <!-- Testttttt -->
        <style>
        p.date__ago{
          font-weight: normal;
            margin-bottom: 0px;
        }
        p.date__all{
           font-size: 11px;
        }
        .test-text{
            display: none;
        }
        .tests:hover .test-text{
            display: block;
        }
        .btn.notcall{
            background-color: yellow;
            color:black;
        }
        .btn.callback{
            background-color: orange;
            color:black;
        }
        .btn.sell{
            background-color: green;
            color:black;
        }
        .btn.off{
            background-color: red;
            color:black;
        }
        div.crm-list-stage-bar {
background: #fff;
border: 1px solid #cdd0d3;
border-radius: 2px;
height: 8px;
min-width: 170px;
max-width: 350px;
position: relative;
}
table.crm-list-stage-bar-table {
border-spacing: 0;
height: 8px;
width: 100%;
}
table.crm-list-stage-bar-table td.crm-list-stage-bar-part div.crm-list-stage-bar-block {
cursor: pointer;
height: 8px;
margin-right: -1px;
min-width: 5px;
position: relative;
}
table.crm-list-stage-bar-table td.crm-list-stage-bar-part div.crm-list-stage-bar-block div.crm-list-stage-bar-btn {
border-top: 3px solid rgba(111,113,115,.39);
border-bottom: 3px solid rgba(111,113,115,.39);
display: none;
height: 100%;
left: -1px;
top: -3px;
right: 0;
position: absolute;
width: 100%;
}
        </style>
        <!-- Contacts -->
        <table class="table tablesaw" data-tablesaw-mode="stack">
          <thead>
            <tr>
              <th class="cell-60" scope="col" data-tablesaw-sortable-col data-tablesaw-priority="3">
                <div class="checkbox-custom checkbox-primary checkbox-lg contacts-select-all select-all">
                  <input type="checkbox" class="contacts-checkbox" id="select_all" />
                  <label for="select_all"></label>
                </div>
              </th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="1">ID</th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">Дата</th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">Контакт</th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">Данные заявки</th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">Комментарий</th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">Статус</th>
            </tr>
          </thead>
          <tbody>
            {% for bid in user_bids %}
            <tr data-url="{% static 'html/panel.tpl' %}" data-toggle="">{# slidePanel #}
              <td data-url="{% static 'html/panel.tpl' %}" data-toggle="slidePanel" class="cell-60 responsive-hide">
                <div class="checkbox-custom checkbox-primary checkbox-lg multi-select">
                  <input type="checkbox" class="contacts-checkbox" id="contacts_1" />
                  <label for="contacts_1"></label>
                </div>
              </td>
              <td>
                <span class="tablesaw-cell-content">{{ bid.id }}</span>
              </td>
              <td><p class="date__ago">{% if forloop.counter == 1 %}Только что{% elif forloop.counter == 2 %}Два часа назад{% else %}1 день назад{% endif %}</p><p class="date__all">{{ bid.created|date:"j.n.Y H:i" }}</p></td>
              <td><b>Имя:</b> {{ bid.bid.name_customer }}<br> <b>Телефон:</b> {{ bid.bid.phone_customer }}</td>
              <td><b>Тематика:</b> {% for t in bid.topic.all  %}{{ t.name }}{% endfor %}</td>
                <td><div data-plugin="summernote" data-air-mode="true" style="width: 180px;max-width: 180px;border: 1px dashed #cccccc;padding: 6px 10px;border-radius: 3px;" class="note-air-editor note-editable" id="note-editor-1" contenteditable="true">{{ bid.bid.commentary }}</div></td>

                <td>{{ settings.status.all }}
                  <select data-plugin="selectpicker" id="selectpicker_{{ bid.id }}" data-style="{% if bid.status_callback.value == 1 %}btn-primary{% elif bid.status_callback.value == 2 %}btn-info{% elif bid.status_callback.value == 3 %}btn-warning{% elif bid.status_callback.value == 4 %}btn-success{% elif bid.status_callback.value == 5 %}btn-danger{% endif %}" class="selectpicker bs-select-hidden">
                      {% for st in settings.status.all %}
                    <option value="{{ st.value }}" {% if  bid.status_callback.value == st.value %}selected{% endif %}>{{ st.choice }}</option>
                      {% endfor %}
                  </select>
              </td>
            </tr>
            {% endfor %}

          </tbody>
        </table>

        <ul data-plugin="paginator" data-total="3" data-skin="pagination-gap"></ul>

 <!-- Add Mail Form -->
  <div class="site-action animation-duration-300">
    <button type="button" class="btn-raised btn btn-success btn-floating">
      <i class="front-icon wb-plus animation-scale-up" aria-hidden="true"></i>
      <i class="back-icon wb-close animation-scale-up" aria-hidden="true"></i>
    </button>
    <div class="site-action-buttons">
      <button type="button" class="btn-raised btn btn-success btn-floating animation-slide-bottom animation-delay-100">
        <i class="icon wb-trash" aria-hidden="true"></i>
      </button>
      <button type="button" class="btn-raised btn btn-success btn-floating animation-slide-bottom">
        <i class="icon wb-folder" aria-hidden="true"></i>
      </button>
    </div>
  </div>

  <div class="modal fade" id="addUserForm" aria-hidden="true" aria-labelledby="addUserForm"
  role="dialog" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" aria-hidden="true" data-dismiss="modal">×</button>
          <h4 class="modal-title">Create New Contact</h4>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group">
              <input type="text" class="form-control" name="name" placeholder="Name" />
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="phone" placeholder="Phone" />
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="email" placeholder="Email" />
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="address" placeholder="Address" />
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="birthday" placeholder="Birthday"
              />
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" data-dismiss="modal" type="submit">Send</button>
          <a class="btn btn-sm btn-white" data-dismiss="modal" href="javascript:void(0)">Cancel</a>
        </div>
      </div>
    </div>
  </div>


{% endblock %}
{% block script %}
<!-- Core  -->
  <script src="{% static 'vendor/jquery/jquery.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/bootstrap.js' %}"></script>
  <script src="{% static 'vendor/animsition/jquery.animsition.js' %}"></script>
  <script src="{% static 'vendor/asscroll/jquery-asScroll.js' %}"></script>
  <script src="{% static 'vendor/mousewheel/jquery.mousewheel.js' %}"></script>
  <script src="{% static 'vendor/asscrollable/jquery.asScrollable.all.js' %}"></script>
  <script src="{% static 'vendor/ashoverscroll/jquery-asHoverScroll.js' %}"></script>

  <!-- Plugins -->
  <script src="{% static 'vendor/switchery/switchery.min.js' %}"></script>
  <script src="{% static 'vendor/intro-js/intro.js' %}"></script>
  <script src="{% static 'vendor/screenfull/screenfull.js' %}"></script>
  <script src="{% static 'vendor/slidepanel/jquery-slidePanel.js' %}"></script>

  <script src="{% static 'vendor/filament-tablesaw/tablesaw.js' %}"></script>
  <script src="{% static 'vendor/slidepanel/jquery-slidePanel.js' %}"></script>
  <script src="{% static 'vendor/aspaginator/jquery.asPaginator.min.js' %}"></script>

    <script src="{% static 'vendor/bootstrap-select/bootstrap-select.min.js' %}"></script>
  <!-- Scripts -->
  <script src="{% static 'js/core.js' %}"></script>
  <script src="{% static 'js/site.js' %}"></script>

  <script src="{% static 'js/sections/menu.js' %}"></script>
  <script src="{% static 'js/sections/menubar.js' %}"></script>
  <script src="{% static 'js/sections/sidebar.js' %}"></script>
  <script src="{% static 'js/sections/footer.js' %}"></script>

  <script src="{% static 'js/configs/config-colors.js' %}"></script>
  <script src="{% static 'js/configs/config-tour.js' %}"></script>

  <script src="{% static 'js/components/asscrollable.js' %}"></script>
  <script src="{% static 'js/components/animsition.js' %}"></script>
  <script src="{% static 'js/components/slidepanel.js' %}"></script>
  <script src="{% static 'js/components/switchery.js' %}"></script>



  <script src="{% static 'js/plugins/sticky-header.js' %}"></script>
  <script src="{% static 'js/components/aspaginator.js' %}"></script>
  <script src="{% static 'js/apps/app.js' %}"></script>
  <script src="{% static 'js/apps/contacts.js' %}"></script>
     <script>
    (function(document, window, $) {
      'use strict';
      var AppContacts = window.AppContacts;

      $(document).ready(function() {
        AppContacts.run();
      });

        $('.selectpicker').selectpicker({
      size: 6
  });
        //$('.selectpicker').selectpicker('setStyle', 'btn-danger');
        $('.dropdown-menu.inner > li').click(function(){
            var res = $(this).data('originalIndex');
            var id = $(this).parents('.tablesaw-cell-content').find('.selectpicker').attr('id');
            console.log(res, id);
            if(res==0) {
                $('#'+id).selectpicker('setStyle', 'btn-warning btn-success btn-info btn-danger', 'remove');
                $('#'+id).selectpicker('setStyle', 'btn-primary');
            }
            else if(res==1) {
                $('#'+id).selectpicker('setStyle', 'btn-warning btn-success btn-primary btn-danger', 'remove');
                $('#'+id).selectpicker('setStyle', 'btn-info');
            }
            else if(res==2) {
                $('#'+id).selectpicker('setStyle', 'btn-primary btn-success btn-info btn-danger', 'remove');
                $('#'+id).selectpicker('setStyle', 'btn-warning');
            }
            else if(res==3) {
                $('#'+id).selectpicker('setStyle', 'btn-warning btn-primary btn-info btn-danger', 'remove');
                $('#'+id).selectpicker('setStyle', 'btn-success');
            }
            else if(res==4) {
                $('#'+id).selectpicker('setStyle', 'btn-primary btn-success btn-info btn-warning', 'remove');
                $('#'+id).selectpicker('setStyle', 'btn-danger');
            }
         });

    })(document, window, jQuery);
  </script>

{% endblock %}

templates/menu.html
<ul>  {% with u=request.resolver_match.url_name %}
      <li>
        <a {% if u == 'user_leads' %}style="background-color: rgba(255,255,255,.02);color:white"{% endif %} href="{% url 'core:user_leads' %}">
          <i class="icon pe-mail"></i>
          <span>Заявки</span>
        </a>
      </li>
      <li>
        <a {% if u == 'user_stats' %}style="background-color: rgba(255,255,255,.02);color:white"{% endif %} href="{% url 'core:user_stats' %}">
          <i class="icon pe-graph3"></i>
          <span>Статистика</span>
        </a>
      </li>
      <li>
        <a {% if u == 'user_settings' %}style="background-color: rgba(255,255,255,.02);color:white"{% endif %} href="{% url 'core:user_settings' %}">
          <i class="icon pe-config"></i>
          <span>Настройки</span>
        </a>
      </li>
      <li>
        <a {% if u == 'user_billing' %}style="background-color: rgba(255,255,255,.02);color:white"{% endif %} href="{% url 'core:user_billing' %}">
          <i class="icon pe-wallet"></i>
          <span>Баланс</span>
        </a>
      </li>
      <li>
        <a {% if u == 'user_company' %}style="background-color: rgba(255,255,255,.02);color:white"{% endif %} href="{% url 'core:user_company' %}">
          <i class="icon ion-ios-briefcase-outline"></i>
          <span>Компания</span>
        </a>
      </li>
      <li >
        <a href="{% url "django.contrib.auth.views.logout" %}?next=/">
          <i class="icon pe-power"></i>
          <span>Выйти</span>
        </a>
      </li>
    </ul>
    {% endwith %}