app/padmin/urls.py
from django.conf.urls import patterns, url
from padmin.views import *

urlpatterns = patterns('',
    url(r'^$', AdminUserListView.as_view(), name='admin_users'),

    url(r'^stats/$', AdminStatisticsView.as_view(), name='admin_stats'),
    url(r'^leads/$', AdminLeadsView.as_view(), name='admin_leads'),
    url(r'^partners/$', AdminPartnersView.as_view(), name='admin_partners'),
    url(r'^settings/$', AdminSettingsView.as_view(), name='admin_settings'),


    #url(r'^bids/$', UserBidsListView.as_view(), name='user_bids'),



)

oxiv/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from rest_framework import routers
from yandex_money.views import CheckOrderFormView
from yandex_money.views import NoticeFormView
from accounts.views import new_registration_user
from core.views import UserBalanceView, test_aviso, test_check_order

admin.autodiscover()



urlpatterns = [
    #url("", include("django_socketio.urls")),
    #url('^chat/', include("chat.urls")),

    url('', include('core.urls', namespace="core")),
    url('^adm/', include('padmin.urls', namespace="padmin")),
    url('^api/', include('api.urls', namespace="api_websocket")),
    url('^manager/', include('core.urls', namespace="manager")),

    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),

    url(r'^registration/', new_registration_user, name='new_registration_user'),

    url(r'^accounts/', include('registration.backends.default.urls')),

    url(r'^fail-payment/$', UserBalanceView.as_view(), name='payment_fail'),
    url(r'^success-payment/$', UserBalanceView.as_view(), name='payment_success'),

    #url(r'^yandex-money/aviso/$', test_aviso, name='test_aviso'),
    #url(r'^yandex-money/check/$', test_check_order, name='test_check_order'),
    url(r'^yandex-money/check/$', CheckOrderFormView.as_view(), name='yandex_money_check'),
    url(r'^yandex-money/aviso/$', NoticeFormView.as_view(), name='yandex_money_notice'),

    #url(r'^yandex-money/', include('yandex_money.urls')),


    url(r'^admin/', include(admin.site.urls)),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/administrator/leads.html
{% extends 'administrator/base.html' %}
{% load staticfiles %}

{% block title %}Статистика | Oxiv.ru{% endblock %}
{% block description %}Какое та описание{% endblock %}
{% block canonical %}{% endblock %}


{% block style_page %}page-content container-fluid{% endblock %}

{% block page_title %}Заявки{% endblock %}

{% block body_class %}app-contacts page-profile{% endblock %}

{% block content %}
<div class="panel">
   <div class="panel-body page-content-table ">
<!-- Actions -->
        <div style="display: none;" class="page-content-actions">
          <div class="pull-right">
            <div class="dropdown">
              <button type="button" class="btn btn-pure dropdown-toggle" data-toggle="dropdown"
              aria-expanded="false">
                More
                <span class="icon wb-chevron-down-mini" aria-hidden="true"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><a href="javascript:void(0)">More</a></li>
                <li><a href="javascript:void(0)">More</a></li>
              </ul>
            </div>
            <button type="button" class="btn btn-outline btn-default btn-md empty-btn">Empty All</button>
          </div>
          <div class="btn-group">
            <div class="dropdown">
              <button class="btn btn-icon btn-pure btn-default dropdown-toggle" data-toggle="dropdown"
              aria-expanded="false" type="button"><i class="icon wb-folder" aria-hidden="true"></i></button>
              <ul class="dropdown-menu" role="menu">
                <li><a href="javascript:void(0)">work</a></li>
                <li><a href="javascript:void(0)">Family</a></li>
                <li><a href="javascript:void(0)">Private</a></li>
                <li><a href="javascript:void(0)">Friends</a></li>
                <li class="divider"></li>
                <li><a href="javascript:void(0)">Trash</a></li>
                <li><a href="javascript:void(0)">Spam</a></li>
              </ul>
            </div>
            <div class="dropdown">
              <button class="btn btn-icon btn-pure btn-default dropdown-toggle" data-toggle="dropdown"
              aria-expanded="false" type="button"><i class="icon wb-tag" aria-hidden="true"></i></button>
              <ul class="dropdown-menu" role="menu">
                <li><a href="javascript:void(0)">work</a></li>
                <li><a href="javascript:void(0)">Family</a></li>
                <li><a href="javascript:void(0)">Private</a></li>
                <li><a href="javascript:void(0)">Friends</a></li>
              </ul>
            </div>
          </div>
        </div>


        <!-- Contacts -->{% include 'administrator/leads/leads_form_edit.html' %}
        <table class="table tablesaw" data-tablesaw-mode="stack">
          <thead>
            <tr>
              <!--<th class="cell-60" scope="col" data-tablesaw-sortable-col data-tablesaw-priority="3">
                <div class="checkbox-custom checkbox-primary checkbox-lg contacts-select-all select-all">
                  <input type="checkbox" class="contacts-checkbox" id="select_all" />
                  <label for="select_all"></label>
                </div>
              </th>-->
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="1">ID</th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">Дата</th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">Контакт</th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">Тематика</th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">Комментарий</th>
            </tr>
          </thead>
          <tbody>
            {% for bid in leads %}
            <tr >{# slidePanel #}
              <!--<td data-url="{% static 'html/panel.tpl' %}" data-toggle="slidePanel" class="cell-60 responsive-hide">
                <div class="checkbox-custom checkbox-primary checkbox-lg multi-select">
                  <input type="checkbox" class="contacts-checkbox" id="contacts_1" />
                  <label for="contacts_1"></label>
                </div>
              </td>-->
              <td data-target="#AdmLeadsEditFrom" data-toggle="modal">
                <span class="tablesaw-cell-content">{{ bid.id }}</span>
              </td>
              <td data-target="#AdmLeadsEditFrom" data-toggle="modal"><p  class="date__ago">{% if forloop.counter == 1 %}Только что{% elif forloop.counter == 2 %}Два часа назад{% else %}1 день назад{% endif %}</p><p class="date__all">{{ bid.created|date:"j.n.Y, H:i" }}</p></td>
              <td data-target="#AdmLeadsEditFrom" data-toggle="modal">
                  <i class="icon ion-android-person" aria-hidden="true"></i> {{ bid.name_customer }}<br>
                  <i class="icon ion-ios-telephone" aria-hidden="true"></i> {{ bid.phone_customer }}<br>
                  <i class="icon ion-ios-location" aria-hidden="true"></i> {{ bid.city }}</td>
              <td data-target="#AdmLeadsEditFrom" data-toggle="modal"><b></b> {% for t in bid.topic.all  %}{{ t.name }}<br>{% endfor %}</td>
                <td><div data-plugin="summernote"  data-air-mode="true" style="width: 180px;max-width: 180px;border: 1px dashed #cccccc;padding: 6px 10px;border-radius: 3px;" class="note-air-editor note-editable" id="note-editor-1" contenteditable="true">{{ bid.bid.commentary }}</div></td>

            </tr>
            {% endfor %}

          </tbody>
        </table>

        <ul style="display: none;" data-plugin="paginator" data-total="3" data-skin="pagination-gap"></ul>
        <nav>
                    <ul class="pagination">
                      <li>
                        <a href="javascript:void(0)" aria-label="Previous">
                          <span aria-hidden="true">«</span>
                        </a>
                      </li>
                      <li><a href="javascript:void(0)">1</a></li>
                      <li><a href="javascript:void(0)">2</a></li>
                      <li><a href="javascript:void(0)">3</a></li>
                      <li><a href="javascript:void(0)">4</a></li>
                      <li><a href="javascript:void(0)">5</a></li>
                      <li>
                        <a href="javascript:void(0)" aria-label="Next">
                          <span aria-hidden="true">»</span>
                        </a>
                      </li>
                    </ul>
                  </nav>

 <!-- Add Mail Form -->
  <div class="site-action animation-duration-300">
    <button type="button" class="btn-raised btn btn-success btn-floating">
      <i class="front-icon wb-plus animation-scale-up" aria-hidden="true"></i>
      <i class="back-icon wb-close animation-scale-up" aria-hidden="true"></i>
    </button>
    <div class="site-action-buttons">
      <button type="button" class="btn-raised btn btn-success btn-floating animation-slide-bottom animation-delay-100">
        <i class="icon wb-trash" aria-hidden="true"></i>
      </button>
      <button type="button" class="btn-raised btn btn-success btn-floating animation-slide-bottom">
        <i class="icon wb-folder" aria-hidden="true"></i>
      </button>
    </div>
  </div>

  <div class="modal fade" id="addUserForm" aria-hidden="true" aria-labelledby="addUserForm"
  role="dialog" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" aria-hidden="true" data-dismiss="modal">×</button>
          <h4 class="modal-title">Create New Contact</h4>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group">
              <input type="text" class="form-control" name="name" placeholder="Name" />
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="phone" placeholder="Phone" />
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="email" placeholder="Email" />
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="address" placeholder="Address" />
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="birthday" placeholder="Birthday"
              />
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" data-dismiss="modal" type="submit">Send</button>
          <a class="btn btn-sm btn-white" data-dismiss="modal" href="javascript:void(0)">Cancel</a>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>

{% endblock %}

templates/administrator/menu.html
<ul>  {% with u=request.resolver_match.url_name %}
      <li>
        <a {% if u == 'admin_leads' %}style="background-color: rgba(255,255,255,.02);color:white"{% endif %} href="{% url 'padmin:admin_leads' %}">
          <i class="icon pe-mail"></i>
          <span>Заявки</span>
        </a>
      </li>
      <li>
        <a {% if u == 'admin_stats' %}style="background-color: rgba(255,255,255,.02);color:white"{% endif %} href="{% url 'padmin:admin_stats' %}">
          <i class="icon pe-graph3"></i>
          <span>Статистика</span>
        </a>
      </li>
      <li>
        <a {% if u == 'admin_users' %}style="background-color: rgba(255,255,255,.02);color:white"{% endif %} href="{% url 'padmin:admin_users' %}">
          <i class="icon pe-config"></i>
          <span>Пользователи</span>
        </a>
      </li>
      <li>
        <a {% if u == 'admin_partners' %}style="background-color: rgba(255,255,255,.02);color:white"{% endif %} href="{% url 'padmin:admin_partners' %}">
          <i class="icon pe-wallet"></i>
          <span>Партнеры</span>
        </a>
      </li>
      <li>
        <a {% if u == 'admin_settings' %}style="background-color: rgba(255,255,255,.02);color:white"{% endif %} href="{% url 'padmin:admin_settings' %}">
          <i class="icon ion-ios-briefcase-outline"></i>
          <span>Настройки</span>
        </a>
      </li>
      <li >
        <a href="{% url "django.contrib.auth.views.logout" %}?next=/">
          <i class="icon pe-power"></i>
          <span>Выйти</span>
        </a>
      </li>
    </ul>
    {% endwith %}

templates/administrator/partners.html
{% extends 'administrator/base.html' %}
{% load staticfiles %}

{% block title %}Партнеры | Oxiv.ru{% endblock %}
{% block description %}Какое та описание{% endblock %}
{% block canonical %}{% endblock %}


{% block style_page %}page-content container-fluid{% endblock %}

{% block page_title %}Партнеры{% endblock %}
{% block body_class %}page-profile {% endblock %}


{% block content %}
content
{% endblock %}

templates/administrator/settings.html
{% extends 'administrator/base.html' %}
{% load staticfiles %}

{% block title %}Статистика | Oxiv.ru{% endblock %}
{% block description %}Какое та описание{% endblock %}
{% block canonical %}{% endblock %}


{% block style_page %}page-content container-fluid{% endblock %}

{% block page_title %]Настройки{% endblock %}
{% block body_class %}page-profile {% endblock %}


{% block content %}
Настройки
{% endblock %}

templates/administrator/statistics.html
{% extends 'administrator/base.html' %}
{% load staticfiles %}

{% block title %}Статистика | Oxiv.ru{% endblock %}
{% block description %}Какое та описание{% endblock %}
{% block canonical %}{% endblock %}


{% block style_page %}page-content container-fluid{% endblock %}

{% block page_title %}Статистика{% endblock %}
{% block body_class %}page-profile {% endblock %}


{% block content %}
Статистика
{% endblock %}

templates/administrator/users.html
{% extends 'administrator/base.html' %}
{% load staticfiles %}

{% block title %}Пользователи | Oxiv.ru{% endblock %}
{% block description %}Какое та описание{% endblock %}
{% block canonical %}{% endblock %}


{% block style_page %}page-content container-fluid{% endblock %}

{% block page_title %}Пользователи{% endblock %}
{% block body_class %}page-profile {% endblock %}


{% block content %}
content
{% endblock %}